apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
replicas:
- count: 3
  name: simplebank-app
images:
- name: rukevweubio/simplebank:b752c4c73281e76f683090d8bf44abf17b904cda
  newName: rukevweubio/simplebank
  newTag: b752c4c73281e76f683090d8bf44abf17b904cda
