name: SimpleBank DevSecOps CI & CD

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ci-devsecops.yaml'
      - 'Dockerfile'
      - 'src/**'
      - 'terraform-script/**'
      - 'k8s-manifests/**'

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  secret-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run Gitleaks (Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/path" \
            zricethezav/gitleaks:latest detect \
            --source /path \
            --report-path /path/gitleaks.json \
            --report-format json

      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks-secret-scan
          path: gitleaks.json

  checkov-terraform:
    name: Checkov Terraform Security Scan
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install checkov
      - name: Run Checkov Terraform
        run: |
          checkov -d ./terraform-script \
            --framework terraform \
            --output json \
            > checkov-terraform.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: checkov-terraform-report
          path: checkov-terraform.json

  checkov-dockerfile:
    name: Checkov Dockerfile Scan
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install checkov
      - name: Run Checkov Dockerfile
        run: |
          checkov -d ./Dockerfile \
            --framework dockerfile \
            --output json \
            > checkov-dockerfile.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: checkov-dockerfile-report
          path: checkov-dockerfile.json

  checkov-kubernetes:
    name: Checkov Kubernetes Security Scan
    runs-on: ubuntu-latest
    needs: [secret-scan]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install checkov
      - name: Run Checkov Kubernetes
        run: |
          checkov -d ./k8s-manifests \
            --framework kubernetes \
            --output json \
            > checkov-k8s.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: checkov-k8s-report
          path: checkov-k8s.json

  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    needs: [checkov-kubernetes]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: lint-report.json

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [checkov-kubernetes]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: unit-test-report.json

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, unit-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm audit --json > npm-audit.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: dependency-audit-report
          path: npm-audit.json

  codeql-sast:
    name: CodeQL SAST
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck]
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [javascript-typescript]
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t simplebank:${{ github.sha }} .
          docker build -t simplebank:latest .
          docker tag simplebank:${{ github.sha }} rukevweubio/simplebank:${{ github.sha }}
          docker tag simplebank:latest rukevweubio/simplebank:latest
          docker save rukevweubio/simplebank:${{ github.sha }} -o simplebank-image.tar

      - uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: simplebank-image.tar



  trivy-image-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ github.sha }}

      - name: Load Docker Image
        run: docker load -i simplebank-image.tar

      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: rukevweubio/simplebank:${{ github.sha }}
          format: sarif
          output: trivy-image.sarif
          severity: CRITICAL,HIGH

      - uses: actions/upload-artifact@v4
        with:
          name: trivy-image-scan-${{ github.sha }}
          path: trivy-image.sarif


  snyk-security-scan:
    name: Snyk Security Scan (SAST + Container)
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl -fsSL https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SYNK_TOKEN }}

      - name: Snyk SAST Scan
        run: snyk code test --json-file-output=snyk-sast.json || true

      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ github.sha }}

      - name: Load Docker Image
        run: docker load -i simplebank-image.tar

      - name: Snyk Container Scan
        run: snyk container test rukevweubio/simplebank:${{ github.sha }} --json-file-output=snyk-container.json || true

      - uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report-${{ github.sha }}
          path: |
            snyk-sast.json
            snyk-container.json


  docker-push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - trivy-image-scan
      - snyk-security-scan
      - dependency-audit
      - codeql-sast
      - checkov-terraform
      - checkov-dockerfile
      - checkov-kubernetes

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/download-artifact@v4
        with:
          name: docker-image-${{ github.sha }}

      - run: docker load -i simplebank-image.tar

      - run: |
          docker push rukevweubio/simplebank:${{ github.sha }}
          docker push rukevweubio/simplebank:latest
